# Generated by Django 5.1.3 on 2024-11-30 07:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_customuser_address_remove_customuser_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userprofile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
